{{- define "ddai-ms-backend.name" -}}
{{- .Chart.Name | lower -}}
{{- end -}}

{{- define "ddai-ms-backend.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
